/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projectoop;

import java.awt.event.KeyEvent;
import java.io.BufferedReader;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.input.KeyCode;
import javax.swing.*;

/**
 *
 * @author Joshua
 */
public class Forgot extends javax.swing.JFrame {

    FileReader fl = new FileReader("DataBase.txt");
    BufferedReader br = new BufferedReader(fl);

    String line = br.readLine();
    String allLines = "";
    String[] s = line.split(":");

    public Forgot() throws FileNotFoundException, IOException {
        FileReader fl = new FileReader("DataBase.txt");
        BufferedReader br = new BufferedReader(fl);

        String line = br.readLine();
        String allLines = "";
        String[] s = line.split(":");

        setVisible(true);
        setSize(1000, 700);
        setResizable(false);
        setLocationRelativeTo(null);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        emailtxt = new javax.swing.JTextField();
        npasstxt3 = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        npasstxt2 = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        backbtn = new javax.swing.JButton();
        confirmbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.TOP));
        jPanel1.setToolTipText("");

        jLabel4.setText("Re enter password");

        emailtxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                emailtxtKeyPressed(evt);
            }
        });

        npasstxt3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                npasstxt3KeyPressed(evt);
            }
        });

        jLabel2.setText("Email address");

        npasstxt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                npasstxt2KeyPressed(evt);
            }
        });

        jLabel3.setText("New password");

        backbtn.setText("Back");
        backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbtnActionPerformed(evt);
            }
        });

        confirmbtn.setText("Confirm");
        confirmbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(backbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(confirmbtn))
                    .addComponent(emailtxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 195, Short.MAX_VALUE)
                    .addComponent(npasstxt2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(npasstxt3, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(30, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npasstxt2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npasstxt3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backbtn)
                    .addComponent(confirmbtn))
                .addGap(33, 33, 33))
        );

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/projectoop/Untitled-1.png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(330, 330, 330)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(311, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(359, 359, 359))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(286, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmbtnActionPerformed
        if (s[0].contains(emailtxt.getText())) {

            if (emailtxt.getText().equals("") || npasstxt2.getText().equals("") || npasstxt3.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Please fill up the all questions.", "forgot password", JOptionPane.ERROR_MESSAGE);
                emailtxt.setText("");
                npasstxt2.setText("");
                npasstxt3.setText("");

            } else if (npasstxt2.getText().equals(npasstxt3.getText())) {
                try {
                    FileWriter x = new FileWriter("DataBase.txt", false);
                    x.write(emailtxt.getText() + ":" + npasstxt2.getText());
                    x.close();
                    JOptionPane.showMessageDialog(null, "Change password successfully.", "forgot password", JOptionPane.INFORMATION_MESSAGE);

                    Login login = new Login();
                    dispose();

                } catch (IOException ex) {
                    Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
                }
            } else if (npasstxt2.getText() != npasstxt3.getText()) {
                JOptionPane.showMessageDialog(null, "Password doesn't match.", "forgot password", JOptionPane.ERROR_MESSAGE);
                emailtxt.setText("");
                npasstxt2.setText("");
                npasstxt3.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Email address cannot be found.", "forgot password", JOptionPane.ERROR_MESSAGE);
            emailtxt.setText("");
            npasstxt2.setText("");
            npasstxt3.setText("");
        }
    }//GEN-LAST:event_confirmbtnActionPerformed

    private void emailtxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailtxtKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (s[0].contains(emailtxt.getText())) {

                if (emailtxt.getText().equals("") || npasstxt2.getText().equals("") || npasstxt3.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Please fill up the all questions.", "forgot password", JOptionPane.ERROR_MESSAGE);
                    emailtxt.setText("");
                    npasstxt2.setText("");
                    npasstxt3.setText("");

                } else if (npasstxt2.getText().equals(npasstxt3.getText())) {
                    try {
                        FileWriter x = new FileWriter("DataBase.txt", false);
                        x.write(emailtxt.getText() + ":" + npasstxt2.getText());
                        x.close();
                        JOptionPane.showMessageDialog(null, "Change password successfully.", "forgot password", JOptionPane.INFORMATION_MESSAGE);

                        Login login = new Login();
                        dispose();

                    } catch (IOException ex) {
                        Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else if (npasstxt2.getText() != npasstxt3.getText()) {
                    JOptionPane.showMessageDialog(null, "Password doesn't match.", "forgot password", JOptionPane.ERROR_MESSAGE);
                    emailtxt.setText("");
                    npasstxt2.setText("");
                    npasstxt3.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Email address cannot be found.", "forgot password", JOptionPane.ERROR_MESSAGE);
                emailtxt.setText("");
                npasstxt2.setText("");
                npasstxt3.setText("");
            }
        }
    }//GEN-LAST:event_emailtxtKeyPressed

    private void npasstxt2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_npasstxt2KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (s[0].contains(emailtxt.getText())) {

                if (emailtxt.getText().equals("") || npasstxt2.getText().equals("") || npasstxt3.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Please fill up the all questions.", "forgot password", JOptionPane.ERROR_MESSAGE);
                    emailtxt.setText("");
                    npasstxt2.setText("");
                    npasstxt3.setText("");

                } else if (npasstxt2.getText().equals(npasstxt3.getText())) {
                    try {
                        FileWriter x = new FileWriter("DataBase.txt", false);
                        x.write(emailtxt.getText() + ":" + npasstxt2.getText());
                        x.close();
                        JOptionPane.showMessageDialog(null, "Change password successfully.", "forgot password", JOptionPane.INFORMATION_MESSAGE);

                        Login login = new Login();
                        dispose();

                    } catch (IOException ex) {
                        Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else if (npasstxt2.getText() != npasstxt3.getText()) {
                    JOptionPane.showMessageDialog(null, "Password doesn't match.", "forgot password", JOptionPane.ERROR_MESSAGE);
                    emailtxt.setText("");
                    npasstxt2.setText("");
                    npasstxt3.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Email address cannot be found.", "forgot password", JOptionPane.ERROR_MESSAGE);
                emailtxt.setText("");
                npasstxt2.setText("");
                npasstxt3.setText("");
            }
        }
    }//GEN-LAST:event_npasstxt2KeyPressed

    private void npasstxt3KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_npasstxt3KeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            if (s[0].contains(emailtxt.getText())) {

                if (emailtxt.getText().equals("") || npasstxt2.getText().equals("") || npasstxt3.getText().equals("")) {
                    JOptionPane.showMessageDialog(null, "Please fill up the all questions.", "forgot password", JOptionPane.ERROR_MESSAGE);
                    emailtxt.setText("");
                    npasstxt2.setText("");
                    npasstxt3.setText("");

                } else if (npasstxt2.getText().equals(npasstxt3.getText())) {
                    try {
                        FileWriter x = new FileWriter("DataBase.txt", false);
                        x.write(emailtxt.getText() + ":" + npasstxt2.getText());
                        x.close();
                        JOptionPane.showMessageDialog(null, "Change password successfully.", "forgot password", JOptionPane.INFORMATION_MESSAGE);

                        Login login = new Login();
                        dispose();

                    } catch (IOException ex) {
                        Logger.getLogger(Signup.class.getName()).log(Level.SEVERE, null, ex);
                    }
                } else if (npasstxt2.getText() != npasstxt3.getText()) {
                    JOptionPane.showMessageDialog(null, "Password doesn't match.", "forgot password", JOptionPane.ERROR_MESSAGE);
                    emailtxt.setText("");
                    npasstxt2.setText("");
                    npasstxt3.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Email address cannot be found.", "forgot password", JOptionPane.ERROR_MESSAGE);
                emailtxt.setText("");
                npasstxt2.setText("");
                npasstxt3.setText("");
            }
        }
    }//GEN-LAST:event_npasstxt3KeyPressed

    private void backbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbtnActionPerformed
        dispose();
        try {
            Login login = new Login();
        } catch (IOException ex) {
            Logger.getLogger(Forgot.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_backbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Forgot.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                try {
                    new Forgot().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Forgot.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backbtn;
    private javax.swing.JButton confirmbtn;
    private javax.swing.JTextField emailtxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField npasstxt2;
    private javax.swing.JPasswordField npasstxt3;
    // End of variables declaration//GEN-END:variables
}
